In [1]:
# Importation des modules

%run /home/onyxia/work/Advanced_ML_Project/00_Librairies.ipynb

In [4]:
# Téléchargement de MNIST via OpenML
mnist = fetch_openml('mnist_784', version=1)
X, y = mnist['data'], mnist['target']

# Affichage des données
print('Données : \n', X, '\n')
print('Labels : \n', y)

Données : 
        pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69995       0       0       0       0       0       0       0       0       0   
69996       0       0       0       0       0       0       0       0       0   
69997       0       0       0       0       0       0       0       0       0   
69998       0       0       0       0       0       0       0       0       0   
69999       0       0       0       0       0       0       0       0       0   

       pixel10 

In [3]:
# Téléchargement sur le dépôt des données => on ne peut pas les envoyer sur git ensuite

# Sauvegarde des données
#np.save('mnist_data.npy', X)
#np.save('mnist_labels.npy', y)

# Chargement des données
#X = np.load('mnist_data.npy')
#y = np.load('mnist_labels.npy', allow_pickle=True)

# Affichage des données
print('Données : \n', X, '\n')
print('Labels : \n', y)

Données : 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 

Labels : 
 ['5' '0' '4' ... '4' '5' '6']
